apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lp6671yun-go-gitops
  description: This is GitOps manifest for lp6671yun-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: lp6671yun-go
    janus-idp.io/tekton: lp6671yun-go
    backstage.io/kubernetes-id: lp6671yun-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:lp6671yun-go
